/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import Dao.Method;
import Model.registerfile;

/**
 *
 * @author student
 */
public class accountUI extends javax.swing.JFrame {

    /**
     * Creates new form accountUI
     */
    public accountUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        UPID = new javax.swing.JTextField();
        UPPW = new javax.swing.JTextField();
        showinfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showinfo1 = new javax.swing.JTextArea();
        UPdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deleteID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        show3 = new javax.swing.JLabel();
        show2 = new javax.swing.JLabel();
        show1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showBOX = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setText("請輸入帳號");
        ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDMouseClicked(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("輸入帳號後");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("輸入帳號查詢密碼");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jButton1.setText("查詢");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, -1));

        UPID.setText("帳號");
        UPID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPIDMouseClicked(evt);
            }
        });
        jPanel1.add(UPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 130, 30));

        UPPW.setText("修改密碼");
        UPPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPPWMouseClicked(evt);
            }
        });
        jPanel1.add(UPPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 130, 30));

        showinfo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(showinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, 20));

        jScrollPane1.setOpaque(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        showinfo1.setBackground(new java.awt.Color(0, 0, 51));
        showinfo1.setColumns(20);
        showinfo1.setForeground(new java.awt.Color(255, 255, 255));
        showinfo1.setLineWrap(true);
        showinfo1.setRows(3);
        jScrollPane1.setViewportView(showinfo1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 180, 90));

        UPdate.setText("修改");
        UPdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPdateActionPerformed(evt);
            }
        });
        jPanel1.add(UPdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" 輸入要修改的密碼");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("輸入帳號後");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("刪除該帳號");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        deleteID.setText("請輸入要刪除的帳號");
        deleteID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteIDMouseClicked(evt);
            }
        });
        jPanel1.add(deleteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 130, 30));

        jButton2.setText("刪除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        show3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        show3.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.add(show3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 130, 40));

        show2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        show2.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 130, 40));

        show1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        show1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, 40));

        jScrollPane2.setBackground(new java.awt.Color(0, 102, 102));

        showBOX.setBackground(new java.awt.Color(19, 31, 55));
        showBOX.setColumns(20);
        showBOX.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        showBOX.setForeground(new java.awt.Color(0, 204, 204));
        showBOX.setLineWrap(true);
        showBOX.setRows(5);
        showBOX.setText("showBOX");
        showBOX.setAutoscrolls(false);
        jScrollPane2.setViewportView(showBOX);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 240, 190));

        jButton3.setText("返回前頁");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/accountimg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 800, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String username=ID.getText();
     showinfo1.setText(new Method().queryID1(username));
     
     showBOX.append("查詢成功\n");
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMouseClicked
    ID.setText("");
    }//GEN-LAST:event_IDMouseClicked

    private void UPdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPdateActionPerformed
     String UPid=UPID.getText(); 
     String UPpw=UPPW.getText();
    registerfile rf=new Method().queryId(UPid);
    rf.setUsername(UPid);
    rf.setPassword(UPpw);
    new Method().update(rf);
    
    showBOX.append("修改密碼成功\n");
    }//GEN-LAST:event_UPdateActionPerformed

    private void UPIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPIDMouseClicked
UPID.setText("");
    }//GEN-LAST:event_UPIDMouseClicked

    private void UPPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPPWMouseClicked
UPPW.setText("");
    }//GEN-LAST:event_UPPWMouseClicked

    private void deleteIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteIDMouseClicked
deleteID.setText("");
    }//GEN-LAST:event_deleteIDMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new Method().delete(deleteID.getText());

showBOX.append("刪除成功\n");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    new login().setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField UPID;
    private javax.swing.JTextField UPPW;
    private javax.swing.JButton UPdate;
    private javax.swing.JTextField deleteID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel show1;
    private javax.swing.JLabel show2;
    private javax.swing.JLabel show3;
    private javax.swing.JTextArea showBOX;
    private javax.swing.JLabel showinfo;
    private javax.swing.JTextArea showinfo1;
    // End of variables declaration//GEN-END:variables
}
