
package Controller;
import Dao.Method;
import Model.Album;
import Model.account;
import Model.registerfile;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Shopui extends javax.swing.JFrame {
    
    account USER=new account();
    Album A0001=new Album("池堂怪談","0001","魚丁糸",498);
    Album A0002=new Album("明天再見","0002","韋禮安",598);
    Album A0003=new Album("歹勢好勢","0003","拍謝少年",498);
    Album A0004=new Album("30","0004","Adele",498);
    Album A0005=new Album("捍衛戰士","0005","VA",333);
    Album A0006=new Album("THE ALBUM","0006","BlackPink",399);
    Album A0007=new Album("ELZA","0007","REONA",760);
    Album A0008=new Album("幻夢成真：白晝精選","0008","Aimer",1180);
    Album A0009=new Album("LILAC","0009","IU",528);
    Date date = new Date();
    
    
    boolean login=false;
    int j=0;
      public static String Date()
    {
        SimpleDateFormat s=new SimpleDateFormat("MM/dd/yyyy");
        Date d=new Date();      
        return s.format(d);  
    }
    public static String Timer()
    {
        SimpleDateFormat time=new SimpleDateFormat("HH:mm:ss");
        //Timer t=new Timer();         
        Date t=new Date(); 
        return time.format(t);          
    }
    
    

    public Shopui() {
        initComponents();
       times.setText(Date()); 
        new Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                times.setText(Timer());
            }
        },0,1000);
        
    }
    int ri=0;
    
    String registerusername[]=new String[20];
    String registerpassword[]=new String[20];
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        show2 = new javax.swing.JLabel();
        show1 = new javax.swing.JLabel();
        showinfo = new javax.swing.JLabel();
        allcount = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pay1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        times = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.getAccessibleContext().setAccessibleName("");

        show2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        show2.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 170, 30));

        show1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        show1.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(show1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 170, 30));

        showinfo.setBackground(new java.awt.Color(255, 51, 51));
        showinfo.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        showinfo.setForeground(new java.awt.Color(255, 255, 255));
        showinfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showinfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        showinfo.setAutoscrolls(true);
        getContentPane().add(showinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 310, 390));

        allcount.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        allcount.setForeground(new java.awt.Color(255, 0, 153));
        allcount.setText("0");
        getContentPane().add(allcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 30, 40));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel20.setText("購物車數量");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, 150, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel17.setText("加到購物車");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel18.setText("加到購物車");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel19.setText("加到購物車");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel14.setText("加到購物車");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel15.setText("加到購物車");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel16.setText("加到購物車");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel13.setText("加到購物車");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel12.setText("加到購物車");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/IU.png"))); // NOI18N
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/blaclpink.png"))); // NOI18N
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/kart1.png"))); // NOI18N
        jLabel9.setText("加到購物車");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/sorry.png"))); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/reona.jpg"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 150, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/adele30_1.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/aimer.png"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/fish.png"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/top_gun.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 150, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/wei.png"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jButton3.setText("送出訂單");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 83, 140, 30));

        jButton4.setText("匯出");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 630, 70, -1));

        jButton5.setText("清除");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 670, 70, -1));

        pay1.setText("輸入付款金額");
        pay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay1MouseClicked(evt);
            }
        });
        getContentPane().add(pay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 100, 60));

        jButton6.setText("結帳付款");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 630, -1, 60));

        result.setBackground(new java.awt.Color(255, 204, 153));
        result.setColumns(20);
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 120, 270, 500));

        times.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        times.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(times, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 170, 40));

        jButton1.setText("返回前頁");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/BK.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
    String Text="<html>";
    Text+="專輯名稱:池堂怪談<br>";
    Text+="歌手:魚丁糸<br>";
    Text+="編號:0001<br>";
    Text+="價格:498<br>";
    Text+="庫存數量:20<br>";
    Text+="介紹:魚丁糸首張全新專輯《池堂怪談》<br>";
    Text+="人生如戲 有點怪奇…<br>";
    Text+="封存五年的人生原聲帶，高潮迭起。<br>";
    Text+="從〈我就奇怪〉發展到〈終點起點〉，曲折離奇。<br>";
    Text+="一場奇幻搖滾音樂冒險之旅。<br>";
    showinfo.setText(Text);  
    }//GEN-LAST:event_jLabel5MouseMoved

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
    String Text="<html>";
    Text+="專輯名稱:明天再見<br>";
    Text+="歌手:韋禮安<br>";
    Text+="編號:0002<br>";
    Text+="價格:598<br>";
    Text+="庫存數量:20<br>";
    Text+="介紹:中英日韓音樂金榜四冠王韋禮安<br>";
    Text+="從「生活的聲音相簿搜集」<br>";
    Text+="到「生命電影詩的音樂導演」<br>";
    Text+="懷抱著製作「最後一張專輯的心情」<br>";
    Text+="創作出各種形式的「再見」。<br>";
    showinfo.setText(Text);    
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
    String Text="<html>";
    Text+="專輯名稱:歹勢好勢<br>";
    Text+="歌手:拍謝少年<br>";
    Text+="編號:0003<br>";
    Text+="價格:498<br>";
    Text+="庫存數量:20<br>";
    Text+="介紹:拍謝少年第三張台語搖滾專輯<br>";
    Text+="有時歹勢，有時好勢<br>";
    Text+="台語搖滾，今年聽拍謝<br>";
    Text+="〈你愛咱的無仝款〉<br>";
    Text+="變動的時代，多元的價值觀<br>";
    Text+="浮浮沈沈、彎彎曲曲活成自己的模樣。<br>";
    showinfo.setText(Text);   
    }//GEN-LAST:event_jLabel8MouseMoved

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
    String Text="<html>";
    Text+="專輯名稱:30<br>";
    Text+="歌手:Adele<br>";
    Text+="編號:0004<br>";
    Text+="價格:999<br>";
    Text+="庫存數量:5<br>";
    Text+="介紹:愛黛兒的第四張錄音室專輯<br>";
    Text+="為流行、靈魂樂跟爵士樂專輯<br>";
    Text+="聚焦在愛黛兒離婚、焦慮與懷孕等主題<br>";
    Text+="我覺得這張專輯先是自我毀滅<br>";
    Text+="然後是自我反思<br>";
    Text+="以及帶些自我救贖<br>";
    showinfo.setText(Text);    
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
    String Text="<html>";
    Text+="專輯名稱:捍衛戰士<br>";
    Text+="歌手:Various Artists<br>";
    Text+="編號:0005<br>";
    Text+="價格:333<br>";
    Text+="庫存數量:100<br>";
    Text+="介紹:《捍衛戰士》電影原聲帶<br>";
    Text+="將電影畫面融入音樂錄影帶中<br>";
    Text+="總是讓人回味不已且百聽（看）不厭。<br>";
    Text+="Take My Breath Away<br>";
    Text+="Danger Zone<br>";
    Text+="都讓人留下深刻的印象<br>";
    showinfo.setText(Text); 
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
     String Text="<html>";
    Text+="專輯名稱:ELZA<br>";
    Text+="歌手:Reona<br>";
    Text+="編號:0007<br>";
    Text+="價格:760<br>";
    Text+="庫存數量:10<br>";
    Text+="介紹:TV動畫《刀劍神域外傳 Gun Gale Online》<br>";
    Text+="的插曲合輯，所收歌曲均由神崎艾莎<br>";
    Text+=" starring ReoNa演唱。<br>";
    
    showinfo.setText(Text); 
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved

    String Text="<html>";
    Text+="專輯名稱:幻夢成真：白晝精選<br>";
    Text+="歌手:Aimer<br>";
    Text+="編號:0008<br>";
    Text+="價格:1180<br>";
    Text+="庫存數量:10<br>";
    Text+="介紹:而復得的靈性嗓音<br>";
    Text+="跨越命運的新世代歌姬Aimer，<br>";
    Text+="眾所待望的首張精選輯<br>"; 
    Text+="雙版本完整收錄出道曲至最新單曲<br>";
    Text+="並分別收錄兩首新歌更附贈音樂錄影帶DVD<br>";
    showinfo.setText(Text); 
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
    String Text="<html>";
    Text+="專輯名稱:LILAC<br>";
    Text+="歌手:IU<br>";
    Text+="編號:0009<br>";
    Text+="價格:528<br>";
    Text+="庫存數量:10<br>";
    Text+="介紹:IU從開始創作以來許多歌曲都藏了自己懂的暗號<br>";
    Text+="而〈LILAC〉這首歌就是如此<br>";
    Text+="聽起來歡樂的同時，卻是一首寫「分別」的歌曲。<br>"; 
    Text+="你也會在某天將我遺忘吧⋯<br>";
    Text+="連同現在的表情和今天的香氣<br>";
    showinfo.setText(Text);  
    }//GEN-LAST:event_jLabel11MouseMoved

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
  String Text="<html>";
    Text+="專輯名稱:THE ALBUM<br>";
    Text+="歌手:BLACKPINK<br>";
    Text+="編號:0006<br>";
    Text+="價格:399<br>";
    Text+="庫存數量:20<br>";
    Text+="介紹:BLACKPINK的首張韓語正規專輯<br>";
    Text+="此專輯讓BLACKPINK成為KPOP歷史上<br>";
    Text+="第一個GAON榜單銷量破百萬女歌手。<br>";
    Text+="以1,073,671的銷量<br>";
    Text+="站上了10月GAON專輯銷售榜單的第二名<br>";
    showinfo.setText(Text);  
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

    A0001.BuyCD();
    result.append(A0001.Buy());
    allcount.setText(""+Album.ALLcount);
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

    A0002.BuyCD();
    result.append(A0002.Buy());
    allcount.setText(""+Album.ALLcount);    
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

    A0003.BuyCD();
    result.append(A0003.Buy());
    allcount.setText(""+Album.ALLcount);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
    A0004.BuyCD();
    result.append(A0004.Buy());
    allcount.setText(""+Album.ALLcount);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

    A0005.BuyCD();
    result.append(A0005.Buy());
    allcount.setText(""+Album.ALLcount);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
  
    A0006.BuyCD();
    result.append(A0006.Buy());
    allcount.setText(""+Album.ALLcount);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
   
    A0007.BuyCD();
    result.append(A0007.Buy());
    allcount.setText(""+Album.ALLcount);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
    A0008.BuyCD();
    result.append(A0008.Buy());
    allcount.setText(""+Album.ALLcount);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked

    A0009.BuyCD();
    result.append(A0009.Buy());
    allcount.setText(""+Album.ALLcount);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    if(!login)
    {result.append("\n非會員共"+A0009.ALLtotal+"元\n");}
    else {result.append("\n會員價共:"+(int)(A0009.ALLtotal*0.8)+"元\n");}
    
    
    
        /*DefaultTableModel tbModel = (DefaultTableModel) Table.getModel();
        tbModel.addRow(A0001.getData());
        JOptionPane.showMessageDialog(this, "成功加入資料庫");*/// TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
 //輸出資料成TXT檔案，存在上層資料夾
        File file = new File("receipt.txt");
         
        String data = result.getText();
         
        try(FileOutputStream fos = new FileOutputStream(file);
             BufferedOutputStream bos = new BufferedOutputStream(fos)) {
            //convert string to byte array
            byte[] bytes = data.getBytes();
            //write byte array to file
            bos.write(bytes);
            bos.close();
            fos.close();
            System.out.print("Data written to file successfully.");
        } catch (IOException e) {
            e.printStackTrace();
            
        } 
JOptionPane.showMessageDialog(this, "已於資料夾匯出txt檔案", "通知", JOptionPane.INFORMATION_MESSAGE);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
     result.setText("");  
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
    int money=Integer.parseInt(pay1.getText());
      
      int changemoney=money-A0009.ALLtotal;
      int changemoney2=(int)(money-A0009.ALLtotal*0.8);
      if(!login)
      {   
      int a,b,c,d,e,f,g;
      if(changemoney>0)
      {result.append("找零:"+(changemoney)+"\n");
       a=changemoney/1000;
       b=(changemoney-1000*a)/500;
       c=(changemoney-(1000*a+500*b))/100;
       d=(changemoney-(1000*a+500*b+100*c))/50;
       e=(changemoney-(1000*a+500*b+100*c+50*d))/10;
       f=(changemoney-(1000*a+500*b+100*c+50*d+10*e))/5;
       g=(changemoney-(1000*a+500*b+100*c+50*d+10*e+5*f))/1;
       result.append("一千"+a+"張, 五百"+b+"張, 一佰"+c+"張\n");
       result.append("五十"+d+"枚, 十元"+e+"枚, "+"五元"+f+"枚, "+"一元"+g+"枚");
      }
        else{JOptionPane.showMessageDialog(this, "你付的錢不夠!", "注意!注意!", JOptionPane.INFORMATION_MESSAGE);}}
      else
      {int a,b,c,d,e,f,g;
      if(changemoney2>0)
      {result.append("找零:"+(changemoney2)+"\n");
       a=changemoney2/1000;
       b=(changemoney2-1000*a)/500;
       c=(changemoney2-(1000*a+500*b))/100;
       d=(changemoney2-(1000*a+500*b+100*c))/50;
       e=(changemoney2-(1000*a+500*b+100*c+50*d))/10;
       f=(changemoney2-(1000*a+500*b+100*c+50*d+10*e))/5;
       g=(changemoney2-(1000*a+500*b+100*c+50*d+10*e+5*f))/1;
       result.append("一千"+a+"張, 五百"+b+"張, 一佰"+c+"張\n");
       result.append("五十"+d+"枚, 十元"+e+"枚, "+"五元"+f+"枚, "+"一元"+g+"枚");
      }
        else{JOptionPane.showMessageDialog(this, "你付的錢不夠!", "注意!注意!", JOptionPane.INFORMATION_MESSAGE);}}
     
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void pay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay1MouseClicked
    pay1.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_pay1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new login().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shopui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shopui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shopui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shopui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shopui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allcount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pay1;
    private javax.swing.JTextArea result;
    private javax.swing.JLabel show1;
    private javax.swing.JLabel show2;
    private javax.swing.JLabel showinfo;
    private javax.swing.JLabel times;
    // End of variables declaration//GEN-END:variables
}
